# Generated by Django 5.2.8 on 2025-11-08 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('colors', models.JSONField(default=list, help_text='List of brand colors')),
                ('fonts', models.JSONField(default=list, help_text='List of font families')),
                ('logos', models.JSONField(default=list, help_text='List of logo URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kits', to='auth.group')),
            ],
            options={
                'db_table': 'brand_kits',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('canvas_settings', models.JSONField(default=dict)),
                ('presentation_path', models.JSONField(default=list, help_text='Ordered frame IDs for presentation flow')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_presented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brandkit')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presentations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('position', models.JSONField(default=dict, help_text='x, y, width, height, rotation')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.presentation')),
            ],
            options={
                'db_table': 'frames',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('position', models.JSONField(blank=True, help_text='Optional position marker on canvas', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.frame')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.presentation')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cursor_position', models.JSONField(default=dict)),
                ('selected_element_id', models.UUIDField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('channel_name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.presentation')),
            ],
            options={
                'db_table': 'collaboration_sessions',
            },
        ),
        migrations.CreateModel(
            name='PresentationAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('VIEWER', 'Viewer'), ('COMMENTER', 'Commenter'), ('EDITOR', 'Editor')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='api.presentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presentation_access',
            },
        ),
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('EDUCATION', 'Education'), ('BUSINESS', 'Business'), ('MARKETING', 'Marketing'), ('PITCH', 'Pitch Deck'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('structure', models.JSONField(default=dict, help_text='Template structure definition')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presentation_templates',
            },
        ),
        migrations.CreateModel(
            name='PresentationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('snapshot', models.JSONField(help_text='Full presentation data snapshot')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.presentation')),
            ],
            options={
                'db_table': 'presentation_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('recording_url', models.URLField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='api.presentation')),
            ],
            options={
                'db_table': 'recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('ICON', 'Icon'), ('AUDIO', 'Audio')], max_length=20)),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='auth.group')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx'), models.Index(fields=['group'], name='assets_group_i_888d90_idx')],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('SHAPE', 'Shape'), ('ICON', 'Icon'), ('CHART', 'Chart'), ('TABLE', 'Table')], max_length=20)),
                ('position', models.JSONField(default=dict, help_text='x, y, width, height, rotation, z-index')),
                ('content', models.JSONField(default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.frame')),
            ],
            options={
                'db_table': 'elements',
                'indexes': [models.Index(fields=['frame', 'element_type'], name='elements_frame_i_c8ec7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrameConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('trigger_type', models.CharField(default='click', help_text='click, hover, auto', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='api.frame')),
                ('to_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='api.frame')),
            ],
            options={
                'db_table': 'frame_connections',
                'unique_together': {('from_frame', 'to_frame')},
            },
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['owner', 'created_at'], name='presentatio_owner_i_a66762_idx'),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['group'], name='presentatio_group_i_ab6e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['presentation', 'order'], name='frames_present_0323a8_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationsession',
            index=models.Index(fields=['presentation', 'user'], name='collaborati_present_28e8d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presentationaccess',
            unique_together={('presentation', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='presentationversion',
            unique_together={('presentation', 'version_number')},
        ),
    ]
