# Generated by Django 5.2.8 on 2025-11-08 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.TextField()),
                ('background_color', models.CharField(max_length=20)),
                ('background_image', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_frame',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=20)),
                ('file_url', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('tags', models.TextField()),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_asset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('colors', models.TextField()),
                ('fonts', models.TextField()),
                ('logos', models.TextField()),
                ('is_default', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
            options={
                'db_table': 'api_brandkit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element_type', models.CharField(max_length=20)),
                ('position', models.TextField()),
                ('content', models.TextField()),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('frame', models.ForeignKey(db_column='frame_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elements', to='api.frame')),
            ],
            options={
                'db_table': 'api_element',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('canvas_settings', models.TextField()),
                ('presentation_path', models.TextField()),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('is_public', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('brand_kit', models.ForeignKey(blank=True, db_column='brand_kit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.brandkit')),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_presentation',
                'ordering': ['-updated_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='presentation',
            field=models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='frames', to='api.presentation'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('position', models.TextField()),
                ('is_resolved', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(blank=True, db_column='element_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='api.element')),
                ('frame', models.ForeignKey(blank=True, db_column='frame_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='api.frame')),
                ('presentation', models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='api.presentation')),
            ],
            options={
                'db_table': 'api_comment',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cursor_position', models.TextField()),
                ('selected_element_id', models.CharField(blank=True, max_length=36, null=True)),
                ('color', models.CharField(max_length=7)),
                ('channel_name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='api.presentation')),
            ],
            options={
                'db_table': 'api_collaborationsession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccessControlEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField()),
                ('granted_by', models.ForeignKey(blank=True, db_column='granted_by_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='granted_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(blank=True, db_column='presentation_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.presentation')),
            ],
            options={
                'db_table': 'api_accesscontrolentry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PresentationAccess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField()),
                ('granted_by', models.ForeignKey(blank=True, db_column='granted_by_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_grants', to='api.presentation')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_presentationaccess',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('structure', models.TextField()),
                ('is_public', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_presentationtemplate',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='template',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.presentationtemplate'),
        ),
        migrations.CreateModel(
            name='PresentationVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('snapshot', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='api.presentation')),
            ],
            options={
                'db_table': 'api_presentationversion',
                'ordering': ['-version_number'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('recording_url', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('share_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recordings', to='api.presentation')),
            ],
            options={
                'db_table': 'api_recording',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FrameConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('from_frame', models.ForeignKey(db_column='from_frame_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_connections', to='api.frame')),
                ('to_frame', models.ForeignKey(db_column='to_frame_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_connections', to='api.frame')),
            ],
            options={
                'db_table': 'api_frameconnection',
                'managed': True,
                'unique_together': {('from_frame', 'to_frame')},
            },
        ),
    ]
