# Generated by Django 5.2.8 on 2025-11-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_schema_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='animation_settings',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='frame',
            name='transition_settings',
            field=models.TextField(default='{}'),
        ),
    ]
