# Generated by Django 5.2.8 on 2025-11-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('granted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_accesscontrolentry',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='brandkit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='collaborationsession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False, 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'managed': False, 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='frameconnection',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'managed': False, 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='presentationaccess',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='presentationtemplate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='presentationversion',
            options={'managed': False, 'ordering': ['-version_number']},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
