# Generated by Django 5.2.8 on 2025-11-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accesscontrolentry_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='api_asset',
        ),
        migrations.AlterModelTable(
            name='brandkit',
            table='api_brandkit',
        ),
        migrations.AlterModelTable(
            name='collaborationsession',
            table='api_collaborationsession',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='api_comment',
        ),
        migrations.AlterModelTable(
            name='element',
            table='api_element',
        ),
        migrations.AlterModelTable(
            name='frame',
            table='api_frame',
        ),
        migrations.AlterModelTable(
            name='frameconnection',
            table='api_frameconnection',
        ),
        migrations.AlterModelTable(
            name='presentation',
            table='api_presentation',
        ),
        migrations.AlterModelTable(
            name='presentationaccess',
            table='api_presentationaccess',
        ),
        migrations.AlterModelTable(
            name='presentationtemplate',
            table='api_presentationtemplate',
        ),
        migrations.AlterModelTable(
            name='presentationversion',
            table='api_presentationversion',
        ),
        migrations.AlterModelTable(
            name='recording',
            table='api_recording',
        ),
    ]
