# Generated by Django 5.2.8 on 2025-11-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asset_table_alter_brandkit_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesscontrolentry',
            table='accesscontrolentry',
        ),
        migrations.AlterModelTable(
            name='asset',
            table='asset',
        ),
        migrations.AlterModelTable(
            name='brandkit',
            table='brandkit',
        ),
        migrations.AlterModelTable(
            name='collaborationsession',
            table='collaborationsession',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='element',
            table='element',
        ),
        migrations.AlterModelTable(
            name='frame',
            table='frame',
        ),
        migrations.AlterModelTable(
            name='frameconnection',
            table='frameconnection',
        ),
        migrations.AlterModelTable(
            name='presentation',
            table='presentation',
        ),
        migrations.AlterModelTable(
            name='presentationaccess',
            table='presentationaccess',
        ),
        migrations.AlterModelTable(
            name='presentationtemplate',
            table='presentationtemplate',
        ),
        migrations.AlterModelTable(
            name='presentationversion',
            table='presentationversion',
        ),
        migrations.AlterModelTable(
            name='recording',
            table='recording',
        ),
    ]
