# Generated by Django 5.2.8 on 2025-11-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_accesscontrolentry_table_alter_asset_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrolentry',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='brandkit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='collaborationsession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'managed': True, 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='frameconnection',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'managed': True, 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='presentationaccess',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='presentationtemplate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='presentationversion',
            options={'managed': True, 'ordering': ['-version_number']},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
