# Generated by Django 5.1.1 on 2025-11-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('running', 'Running'), ('score_display', 'Score Display'), ('finished', 'Finished')], default='lobby', max_length=15),
        ),
    ]
